### PR TITLE
Exercises/3.1

### PR DESCRIPTION
**Pull request by rafasysop**
Enviando exercicios bloco 3 dia 2 = HTML

### CODE REVIEW

**Comment by edibertooliveira** [comment]
#VQV 🚀🎉

**Comment by Ludilly** [comment]
Boa Rafael!

**Comment by wagnermor** [comment]
# Go Tryber!

**Comment by Moraes-dev** [comment]
Boa!! #VQV

**Comment by tiagaoalb** [comment]
Goog job. You will become a great web developer. #VQV

**Comment by Doug-Fernando** [comment]
Top demais. #VQV

**Pull request merged**
